CREATE TYPE "Role" AS ENUM ('VOTER','ADMIN','ELECTION_OFFICER','AUDITOR');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING','VERIFIED','REJECTED');
CREATE TYPE "ElectionStatus" AS ENUM ('DRAFT','SCHEDULED','OPEN','PAUSED','CLOSED');
CREATE TYPE "AuditSeverity" AS ENUM ('INFO','WARN','CRITICAL');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"nidHash" TEXT NOT NULL UNIQUE,"fullName" TEXT NOT NULL,"email" TEXT,"phone" TEXT,"passwordHash" TEXT NOT NULL,"duressPinHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'VOTER',"verificationStatus" "VerificationStatus" NOT NULL DEFAULT 'PENDING',"biometricCredentialId" TEXT,"hasVoted" BOOLEAN NOT NULL DEFAULT FALSE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Election" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"status" "ElectionStatus" NOT NULL DEFAULT 'DRAFT',"version" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Candidate" ("id" TEXT PRIMARY KEY,"electionId" TEXT NOT NULL,"name" TEXT NOT NULL,"symbol" TEXT,"ballotOrder" INTEGER NOT NULL);
CREATE TABLE "Vote" ("id" TEXT PRIMARY KEY,"electionId" TEXT NOT NULL,"voterId" TEXT NOT NULL,"candidateId" TEXT,"encryptedPayload" TEXT NOT NULL,"receiptHash" TEXT NOT NULL UNIQUE,"previousHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"actorId" TEXT,"action" TEXT NOT NULL,"severity" "AuditSeverity" NOT NULL DEFAULT 'INFO',"metadata" JSONB NOT NULL,"previousHash" TEXT,"entryHash" TEXT NOT NULL UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notice" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"publishedAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Candidate_electionId_ballotOrder_key" ON "Candidate"("electionId","ballotOrder");
CREATE UNIQUE INDEX "Vote_electionId_voterId_key" ON "Vote"("electionId","voterId");
CREATE INDEX "User_role_verificationStatus_idx" ON "User"("role","verificationStatus");
CREATE INDEX "Vote_electionId_createdAt_idx" ON "Vote"("electionId","createdAt");
CREATE INDEX "AuditLog_createdAt_severity_idx" ON "AuditLog"("createdAt","severity");
ALTER TABLE "Candidate" ADD CONSTRAINT "Candidate_electionId_fkey" FOREIGN KEY ("electionId") REFERENCES "Election"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_electionId_fkey" FOREIGN KEY ("electionId") REFERENCES "Election"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_voterId_fkey" FOREIGN KEY ("voterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;